export const LcdNumberStructure = {
  0: {
    cellOne: true,
    cellTwo: true,
    cellThree: true,
    cellFour: false,
    cellFive: true,
    cellSix: true,
    cellSeven: true,
  },
  1: {
    cellOne: false,
    cellTwo: false,
    cellThree: true,
    cellFour: false,
    cellFive: false,
    cellSix: true,
    cellSeven: false,
  },
  2: {
    cellOne: true,
    cellTwo: false,
    cellThree: true,
    cellFour: true,
    cellFive: true,
    cellSix: false,
    cellSeven: true,
  },
  3: {
    cellOne: true,
    cellTwo: false,
    cellThree: true,
    cellFour: true,
    cellFive: false,
    cellSix: true,
    cellSeven: true,
  },
  4: {
    cellOne: false,
    cellTwo: true,
    cellThree: true,
    cellFour: true,
    cellFive: false,
    cellSix: true,
    cellSeven: false,
  },
  5: {
    cellOne: true,
    cellTwo: true,
    cellThree: false,
    cellFour: true,
    cellFive: false,
    cellSix: true,
    cellSeven: true,
  },
  6: {
    cellOne: true,
    cellTwo: true,
    cellThree: false,
    cellFour: true,
    cellFive: true,
    cellSix: true,
    cellSeven: true,
  },
  7: {
    cellOne: true,
    cellTwo: false,
    cellThree: true,
    cellFour: false,
    cellFive: false,
    cellSix: true,
    cellSeven: false,
  },
  8: {
    cellOne: true,
    cellTwo: true,
    cellThree: true,
    cellFour: true,
    cellFive: true,
    cellSix: true,
    cellSeven: true,
  },
  9: {
    cellOne: true,
    cellTwo: true,
    cellThree: true,
    cellFour: true,
    cellFive: false,
    cellSix: true,
    cellSeven: true,
  },
};

export default LcdNumberStructure;
